In [1]:
import pandas as pd
import glob
import os

In [17]:
csv_pattern = os.path.expanduser("~/Desktop/NBA_injuries_project/player_stats_season/nba_*_totals.csv")
files = glob.glob(csv_pattern)
print(f" Found {len(files)} files")

 Found 16 files

In [27]:
all_stat = []

for file_path in files:
    #read in the csv
    df = pd.read_csv(file_path)

    #parse season from filename
    basename = os.path.basename(file_path)
    year_str = basename.split("_")[1:3]
    season = f"{year_str[0]}-{year_str[1]}"


     # Add season column
    df["season"] = season


    # Append to list
    all_stat.append(df)

    print("appended to all_stat")

appended to all_stat
appended to all_stat
appended to all_stat
appended to all_stat
appended to all_stat
appended to all_stat
appended to all_stat
appended to all_stat
appended to all_stat
appended to all_stat
appended to all_stat
appended to all_stat
appended to all_stat
appended to all_stat
appended to all_stat
appended to all_stat

In [28]:

# Step 3: Combine all into one DataFrame
all_seasons_stats = pd.concat(all_stat, ignore_index=True)

In [30]:
all_seasons_stats.head()

,Rk,Player,Age,Team,Pos,G,GS,MP,FG,FGA,...,AST,STL,BLK,TOV,PF,PTS,Trp-Dbl,Awards,Player-additional,season
0,1,Kevin Durant,21,OKC,SF,82,82,3239,794,1668,...,231,112,84,271,171,2472,0,MVP-2ASNBA1,duranke01,2009-10
1,2,LeBron James,25,CLE,SF,76,76,2966,768,1528,...,651,125,77,261,119,2258,4,MVP-1DPOY-4ASNBA1DEF1,jamesle01,2009-10
2,3,Dwyane Wade,28,MIA,SG,77,77,2792,719,1511,...,501,142,82,252,181,2045,0,MVP-5DPOY-10ASNBA1DEF2,wadedw01,2009-10
3,4,Dirk Nowitzki,31,DAL,PF,81,80,3039,720,1496,...,218,70,79,149,208,2027,1,MVP-7ASNBA2,nowitdi01,2009-10
4,5,Kobe Bryant,31,LAL,SG,73,73,2835,716,1569,...,365,113,20,233,187,1970,0,MVP-3DPOY-12ASNBA1DEF1,bryanko01,2009-10

In [32]:
all_seasons_stats.shape

(10451, 34)

In [34]:
df = all_seasons_stats

In [35]:
print(df['season'].unique())
print(df['season'].isna().sum())

['2009-10' '2022-23' '2024-25' '2017-18' '2018-19' '2012-13' '2019-20'
 '2015-16' '2014-15' '2023-24' '2020-21' '2021-22' '2013-14' '2010-11'
 '2011-12' '2016-17']
0

In [36]:
df.head(500)

,Rk,Player,Age,Team,Pos,G,GS,MP,FG,FGA,...,AST,STL,BLK,TOV,PF,PTS,Trp-Dbl,Awards,Player-additional,season
0,1,Kevin Durant,21,OKC,SF,82,82,3239,794,1668,...,231,112,84,271,171,2472,0,MVP-2ASNBA1,duranke01,2009-10
1,2,LeBron James,25,CLE,SF,76,76,2966,768,1528,...,651,125,77,261,119,2258,4,MVP-1DPOY-4ASNBA1DEF1,jamesle01,2009-10
2,3,Dwyane Wade,28,MIA,SG,77,77,2792,719,1511,...,501,142,82,252,181,2045,0,MVP-5DPOY-10ASNBA1DEF2,wadedw01,2009-10
3,4,Dirk Nowitzki,31,DAL,PF,81,80,3039,720,1496,...,218,70,79,149,208,2027,1,MVP-7ASNBA2,nowitdi01,2009-10
4,5,Kobe Bryant,31,LAL,SG,73,73,2835,716,1569,...,365,113,20,233,187,1970,0,MVP-3DPOY-12ASNBA1DEF1,bryanko01,2009-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,387,Alando Tucker,25,MIN,SF,4,0,25,4,9,...,1,0,0,1,1,8,0,NaN,tuckeal02,2009-10
496,388,Jeff Foster,33,IND,C,16,3,255,22,46,...,21,3,4,14,45,49,0,NaN,fosteje01,2009-10
497,389,Brian Cardinal,32,MIN,PF,29,0,267,14,36,...,24,9,3,7,56,48,0,NaN,cardibr01,2009-10
498,390,Matt Carroll,29,DAL,SG,25,0,121,18,50,...,6,5,0,7,13,46,0,NaN,carroma01,2009-10
499,391,Marcus Landry,24,2TM,SF,18,0,111,16,43,...,0,1,2,6,14,44,0,NaN,landrma01,2009-10

In [37]:
df.head(600)

,Rk,Player,Age,Team,Pos,G,GS,MP,FG,FGA,...,AST,STL,BLK,TOV,PF,PTS,Trp-Dbl,Awards,Player-additional,season
0,1,Kevin Durant,21,OKC,SF,82,82,3239,794,1668,...,231,112,84,271,171,2472,0,MVP-2ASNBA1,duranke01,2009-10
1,2,LeBron James,25,CLE,SF,76,76,2966,768,1528,...,651,125,77,261,119,2258,4,MVP-1DPOY-4ASNBA1DEF1,jamesle01,2009-10
2,3,Dwyane Wade,28,MIA,SG,77,77,2792,719,1511,...,501,142,82,252,181,2045,0,MVP-5DPOY-10ASNBA1DEF2,wadedw01,2009-10
3,4,Dirk Nowitzki,31,DAL,PF,81,80,3039,720,1496,...,218,70,79,149,208,2027,1,MVP-7ASNBA2,nowitdi01,2009-10
4,5,Kobe Bryant,31,LAL,SG,73,73,2835,716,1569,...,365,113,20,233,187,1970,0,MVP-3DPOY-12ASNBA1DEF1,bryanko01,2009-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,18,Jalen Green,20,HOU,SG,76,76,2602,566,1359,...,281,59,18,200,131,1683,0,NaN,greenja05,2022-23
596,19,Jordan Poole,23,GSW,PG,82,43,2458,550,1278,...,369,63,21,252,214,1675,0,NaN,poolejo01,2022-23
597,20,Mikal Bridges,26,2TM,SG,83,83,2963,593,1267,...,273,91,61,127,159,1671,0,NaN,bridgmi01,2022-23
598,20,Mikal Bridges,26,PHO,SF,56,56,2040,354,764,...,201,65,45,78,115,965,0,NaN,bridgmi01,2022-23
599,20,Mikal Bridges,26,BRK,SG,27,27,923,239,503,...,72,26,16,49,44,706,0,NaN,bridgmi01,2022-23

In [38]:
#This did not get concatenated in order

In [42]:
# Create a temporary sort column from the first year of the season
df["season_start"] = df["season"].str[:4].astype(int)

# Sort by that
df = df.sort_values(["season_start", "Player"])

# Drop the temporary column
df.drop(columns="season_start", inplace=True)

In [43]:
df.head(600)

,Rk,Player,Age,Team,Pos,G,GS,MP,FG,FGA,...,AST,STL,BLK,TOV,PF,PTS,Trp-Dbl,Awards,Player-additional,season
283,238,A.J. Price,23,IND,PG,56,2,865,145,354,...,106,35,3,59,53,410,0,NaN,priceaj01,2009-10
16,15,Aaron Brooks,25,HOU,PG,82,82,2919,575,1331,...,434,69,14,232,199,1604,0,MIP-1,brookaa01,2009-10
451,360,Aaron Gray,25,2TM,C,32,0,311,42,82,...,22,9,11,18,54,104,0,NaN,grayaa01,2009-10
452,360,Aaron Gray,25,CHI,C,8,0,50,8,21,...,2,0,0,1,10,18,0,NaN,grayaa01,2009-10
453,360,Aaron Gray,25,NOH,C,24,0,261,34,61,...,20,9,11,17,44,86,0,NaN,grayaa01,2009-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9136,340,Alexis AjinÃ§a,22,TOR,C,24,0,265,47,101,...,8,8,14,17,60,114,0,NaN,ajincal01,2010-11
9010,256,Alonzo Gee,23,3TM,SG,56,34,1118,121,264,...,38,40,18,55,94,331,0,NaN,geeal01,2010-11
9011,256,Alonzo Gee,23,SAS,SG,5,0,18,1,3,...,0,0,2,3,3,2,0,NaN,geeal01,2010-11
9012,256,Alonzo Gee,23,WAS,SG,11,5,127,12,27,...,5,7,0,8,10,32,0,NaN,geeal01,2010-11
9013,256,Alonzo Gee,23,CLE,SG,40,29,973,108,234,...,33,33,16,44,81,297,0,NaN,geeal01,2010-11

In [45]:
df.to_csv("/Users/noah/Desktop/NBA_injuries_project/all_seasons_stats.csv", index=False)